from domain.entities.conversion_job import ConversionJob, JobStatus
from typing import Protocol, Optional

class StoragePort(Protocol):
    def download(self, source: str, destination: str) -> None:...
    def upload(self, source: str, destination: str) -> None:...

class QueuePort(Protocol):
    def fetch_job(self) -> Optional[ConversionJob]:...
    def acknowledge_job(self, job_id: str) -> None:...
    def fail_job(self, job_id: str, error_message: str) -> None:...


    
