from src.domain.entities.conversion_job import ConversionJob, JobStatus
from typing import Protocol, Optional
from pathlib import Path

class StoragePort(Protocol):
    def download(self, key: str, dest_path: Path) -> None:...
    def upload(self, target_key: str, source_path: Path) -> None:...

class QueuePort(Protocol):
    async def fetch_job(self) -> Optional[tuple[str, ConversionJob]]:...
    async def acknowledge_job(self, message_id: str) -> None:...
    async def fail_job(self, message_id: str, error_message: str) -> None:...

class JobEventPort(Protocol):
    async def publish(self, job_id: str, status: JobStatus, details: Optional[dict] = None) -> None:...



    
