"""
File encryption service.

Two layers, both rooted in a server-side master key:

1. **In-memory** (``encrypt_file`` / ``decrypt_file``): Fernet (AES-256-CBC +
   HMAC) with a per-user key derived via HKDF. Kept for small payloads and
   backward compatibility.

2. **Streaming** (``encrypt_file_to`` / ``decrypt_file_to``): a chunked
   AES-256-GCM file format that never loads the whole file into memory.
   Used by the worker to encrypt files at rest in object storage.

   File layout::

       magic "TRENC" (5) | version (1) | chunk_size u32 BE (4)
       | salt (16) | nonce_prefix (8) | chunk ciphertexts...

   Each chunk is encrypted with AES-GCM under a per-file key
   ``HKDF(master, salt=file_salt, info=user_id)`` and a 12-byte nonce made of
   the 8-byte per-file random prefix plus a 4-byte chunk counter.

.. note::
   This protects data **at rest** (bucket misconfiguration, leaked S3
   credentials, backups). The server retains the master key, so it is NOT
   zero-knowledge — the worker must be able to decrypt to convert.
"""

import base64
import io
import os
from base64 import urlsafe_b64encode
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import BinaryIO

from cryptography.fernet import Fernet
from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

_STREAM_MAGIC = b"TRENC"
_STREAM_VERSION = b"\x01"
_SALT_LEN = 16
_NONCE_PREFIX_LEN = 8
_STREAM_HEADER_LEN = len(_STREAM_MAGIC) + 1 + 4 + _SALT_LEN + _NONCE_PREFIX_LEN
DEFAULT_CHUNK_SIZE = 1024 * 1024  # 1 MiB chunks

# Application context prefix bound into the AES-GCM AAD so ciphertext cannot be
# replayed/decrypted under a different application context or user identity.
_APP_AAD_PREFIX = b"transform-v1:"

# ---------------------------------------------------------------------------
# Client-side encryption format ("FENCR" v1)
#
# The browser (WebCrypto) encrypts files BEFORE upload with a NEW format so the
# server never sees plaintext content. This is the mirror of the JS format and
# is byte-compatible with it — verified against a fixed golden vector.
#
#   header = MAGIC("FENCR") + VERSION(\x01) + chunk_size u32 BE (4)
#            + salt (16) + nonce_prefix (8)                    # 34 bytes
#   blob   = header + for each chunk: AESGCM_encrypt(nonce, chunk, AAD)
#
#   file_key = HKDF(SHA-256, length=32, salt=salt, info=b"transform-client-v1:enc")
#   aad      = b"transform-client-v1"
#   nonce    = nonce_prefix + counter.to_bytes(4, "big")    # counter starts at 0
#
# The client generates a random 32-byte ``data_key``. The server NEVER persists
# it in the clear: it wraps the raw key with the existing per-user Fernet key
# (``encrypt_file`` + ``derive_user_key``) and stores only the ciphertext. The
# worker unwraps it with ``decrypt_file`` to recover the raw key for FENCR
# decryption before conversion.
#
# .. note::
#   This is client-side / zero-knowledge encryption: the server only ever has
#   the wrapped data key and the FENCR ciphertext, never the plaintext content
#   nor the raw data key at rest.
# ---------------------------------------------------------------------------
_FENCR_MAGIC = b"FENCR"
_FENCR_VERSION = b"\x01"
_FENCR_SALT_LEN = 16
_FENCR_NONCE_PREFIX_LEN = 8
# GCM tag length in bytes (AES-GCM appends a 16-byte tag to each ciphertext).
_FENCR_TAG_LEN = 16
# AAD bound into AES-GCM for the client-side format.
_FENCR_AAD = b"transform-client-v1"
# HKDF info string for deriving the per-file FENCR key from the raw data key.
_FENCR_HKDF_INFO = b"transform-client-v1:enc"
_FENCR_HEADER_LEN = len(_FENCR_MAGIC) + 1 + 4 + _FENCR_SALT_LEN + _FENCR_NONCE_PREFIX_LEN  # 34


def _validate_master_key(key: bytes) -> None:
    """Validate a Fernet-format master key (base64 of 32 raw bytes)."""
    try:
        decoded = base64.urlsafe_b64decode(key)
    except Exception as exc:
        raise ValueError(
            "Invalid master key: not a valid base64 Fernet key."
        ) from exc
    if len(decoded) != 32:
        raise ValueError(
            "Invalid master key: must decode to a 32-byte Fernet key."
        )


class FileEncryptionService:
    """Encrypts and decrypts files using AES-256 with per-user key derivation."""

    def __init__(
        self,
        master_key: bytes | None = None,
        previous_master_keys: list[bytes] | None = None,
        *,
        allow_autogenerated_key: bool = False,
    ):
        """
        Initialize the encryption service.

        Args:
            master_key: Fernet-compatible master key bytes. Required unless
                ``allow_autogenerated_key`` is True.
            previous_master_keys: Optional older master keys to support key
                rotation. ``decrypt`` tries the current key first, then each
                previous key in order.
            allow_autogenerated_key: Explicit dev/test convenience — when True
                and no ``master_key`` is given, a random key is generated.
                This is a footgun in production and therefore opt-in only.
        """
        if master_key is None:
            if not allow_autogenerated_key:
                raise ValueError(
                    "A master_key is required to build FileEncryptionService. "
                    "Set allow_autogenerated_key=True only for tests/local dev."
                )
            master_key = Fernet.generate_key()
        _validate_master_key(master_key)
        for previous in previous_master_keys or ():
            _validate_master_key(previous)
        self._master_fernet = Fernet(master_key)
        self._master_key = master_key
        self._previous_master_keys = list(previous_master_keys or [])

    # ------------------------------------------------------------------
    # Key derivation
    # ------------------------------------------------------------------

    def derive_user_key(self, user_id: str) -> bytes:
        """
        Derive a user-specific Fernet key from the master key using HKDF.

        Args:
            user_id: Unique user identifier used as info.

        Returns:
            base64-encoded 32-byte key suitable for Fernet.
        """
        hkdf = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=None,
            info=user_id.encode("utf-8"),
        )
        return urlsafe_b64encode(hkdf.derive(self._master_key))

    def _build_aad(self, user_id: str) -> bytes:
        """Build the authenticated associated data binding ciphertext to a user.

        The app context prefix plus the user id is bound into AES-GCM so a
        ciphertext written under one user's key cannot be replayed/decrypted
        under a different user identity or application context.
        """
        return _APP_AAD_PREFIX + user_id.encode("utf-8")

    def _derive_stream_key(self, salt: bytes, user_id: str, master_key: bytes | None = None) -> bytes:
        """Derive a per-file raw 32-byte AES key from a master key.

        Defaults to the current master key; pass ``master_key`` explicitly for
        key-rotation decryption attempts.
        """
        master = master_key if master_key is not None else self._master_key
        hkdf = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            info=user_id.encode("utf-8"),
        )
        return hkdf.derive(master)

    # ------------------------------------------------------------------
    # In-memory (Fernet) API
    # ------------------------------------------------------------------

    def encrypt_file(self, data: bytes, user_id: str) -> bytes:
        """
        Encrypt file data for a specific user (in memory).

        Args:
            data: Raw file bytes to encrypt.
            user_id: User identifier for key derivation.

        Returns:
            Encrypted ciphertext bytes.
        """
        user_key = self.derive_user_key(user_id)
        f = Fernet(user_key)
        return f.encrypt(data)

    def decrypt_file(self, ciphertext: bytes, user_id: str) -> bytes:
        """
        Decrypt file data for a specific user (in memory).

        Args:
            ciphertext: Encrypted bytes to decrypt.
            user_id: User identifier for key derivation.

        Returns:
            Decrypted plaintext bytes.
        """
        user_key = self.derive_user_key(user_id)
        f = Fernet(user_key)
        return f.decrypt(ciphertext)

    # ------------------------------------------------------------------
    # Streaming (AES-256-GCM) API — safe for large files
    # ------------------------------------------------------------------

    def encrypt_stream(
        self,
        src: BinaryIO,
        dst: BinaryIO,
        user_id: str,
        chunk_size: int = DEFAULT_CHUNK_SIZE,
    ) -> None:
        """Encrypt ``src`` into ``dst`` in chunks without buffering the file."""
        if chunk_size <= 0:
            raise ValueError("chunk_size must be a positive integer")

        salt = os.urandom(_SALT_LEN)
        nonce_prefix = os.urandom(_NONCE_PREFIX_LEN)
        file_key = self._derive_stream_key(salt, user_id)
        cipher = AESGCM(file_key)
        aad = self._build_aad(user_id)

        dst.write(_STREAM_MAGIC)
        dst.write(_STREAM_VERSION)
        dst.write(chunk_size.to_bytes(4, "big"))
        dst.write(salt)
        dst.write(nonce_prefix)

        counter = 0
        while True:
            chunk = src.read(chunk_size)
            if not chunk:
                break
            if counter >= 2**32:
                raise OverflowError("File too large: chunk counter exhausted")
            nonce = nonce_prefix + counter.to_bytes(4, "big")
            dst.write(cipher.encrypt(nonce, chunk, aad))
            counter += 1

    def decrypt_stream(self, src: BinaryIO, dst: BinaryIO, user_id: str) -> None:
        """Decrypt a stream produced by :meth:`encrypt_stream` into ``dst``."""
        for chunk in self.iter_decrypt(src.read, user_id):
            dst.write(chunk)

    def encrypt_file_to(
        self,
        input_path: str | Path,
        output_path: str | Path,
        user_id: str,
        chunk_size: int = DEFAULT_CHUNK_SIZE,
    ) -> None:
        """Encrypt a file on disk into a ciphertext file on disk."""
        with open(input_path, "rb") as src, open(output_path, "wb") as dst:
            self.encrypt_stream(src, dst, user_id, chunk_size=chunk_size)

    def decrypt_file_to(
        self,
        input_path: str | Path,
        output_path: str | Path,
        user_id: str,
    ) -> None:
        """Decrypt a ciphertext file on disk into a plaintext file on disk."""
        with open(input_path, "rb") as src, open(output_path, "wb") as dst:
            self.decrypt_stream(src, dst, user_id)

    def is_encrypted_file(self, path: str | Path) -> bool:
        """
        Return True when ``path`` begins with the streaming ciphertext magic.

        Used by the worker (and download path) to decide whether a stored
        object is at-rest ciphertext or plaintext. Because uploads are written
        to object storage directly from the browser (no ingest-time
        encryption), an object may legitimately be plaintext even when
        ``ENCRYPTION_MASTER_KEY`` is configured — in that case we must pass it
        through rather than failing to "decrypt" it.
        """
        try:
            with open(path, "rb") as f:
                return f.read(len(_STREAM_MAGIC)) == _STREAM_MAGIC
        except OSError:
            return False

    def iter_decrypt(
        self,
        read_chunk: Callable[[int], bytes],
        user_id: str,
    ) -> Iterator[bytes]:
        """
        Yield decrypted chunks from an arbitrary chunk-reading callback.

        This enables memory-bounded streaming decryption of objects fetched
        from storage (e.g. Minio ``get_object`` responses) without writing the
        whole file to disk.

        Args:
            read_chunk: Callable that returns exactly ``n`` bytes (or fewer at
                end of stream).
            user_id: User identifier for key derivation.

        Raises:
            ValueError: If the header is missing/invalid.
        """
        header = read_chunk(_STREAM_HEADER_LEN)
        if len(header) != _STREAM_HEADER_LEN or not header.startswith(_STREAM_MAGIC):
            raise ValueError("Not a Transform-encrypted file (bad header)")

        version = header[len(_STREAM_MAGIC)]
        if version != _STREAM_VERSION[0]:
            raise ValueError(f"Unsupported encryption format version: {version}")

        chunk_size = int.from_bytes(
            header[len(_STREAM_MAGIC) + 1: len(_STREAM_MAGIC) + 5], "big"
        )
        salt = header[len(_STREAM_MAGIC) + 5: len(_STREAM_MAGIC) + 5 + _SALT_LEN]
        nonce_prefix = header[len(_STREAM_MAGIC) + 5 + _SALT_LEN: _STREAM_HEADER_LEN]

        aad = self._build_aad(user_id)

        # Read the first chunk up front so key selection can be decided here.
        # AES-GCM decryption with the wrong key raises InvalidTag without
        # consuming the buffer, so we can probe each candidate key in turn.
        first = read_chunk(chunk_size + 16)
        if not first:
            return  # empty ciphertext — nothing to yield

        nonce0 = nonce_prefix + (0).to_bytes(4, "big")
        selected: AESGCM | None = None
        for master in [self._master_key, *self._previous_master_keys]:
            file_key = self._derive_stream_key(salt, user_id, master_key=master)
            candidate = AESGCM(file_key)
            try:
                plain = candidate.decrypt(nonce0, first, aad)
            except InvalidTag:
                continue  # wrong key / tampered — try the next candidate
            selected = candidate
            yield plain
            break

        if selected is None:
            raise ValueError(
                "Failed to decrypt: no matching key (tampered data or unknown key)."
            )

        counter = 1
        while True:
            chunk = read_chunk(chunk_size + 16)  # ciphertext + GCM tag
            if not chunk:
                break
            nonce = nonce_prefix + counter.to_bytes(4, "big")
            yield selected.decrypt(nonce, chunk, aad)
            counter += 1

    # ------------------------------------------------------------------
    # Client-side encryption ("FENCR") — decrypt-only
    # ------------------------------------------------------------------

    def _derive_fencr_file_key(self, salt: bytes, data_key: bytes) -> bytes:
        """Derive the per-file FENCR AES-256-GCM key from a raw data key.

        Mirrors WebCrypto's ``HKDF(SHA-256, salt=salt, info=b'...enc').derive``:
        the raw 32-byte ``data_key`` is the input key material, the FENCR blob's
        salt is the HKDF salt, and the domain-separation info is
        ``b\"transform-client-v1:enc\"``.
        """
        hkdf = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            info=_FENCR_HKDF_INFO,
        )
        return hkdf.derive(data_key)

    def is_fencr_file(self, path: str | Path | bytes) -> bool:
        """
        Return True when ``path`` (or the given bytes) begins with the FENCR
        magic used by client-side encrypted uploads.

        Unlike :meth:`is_encrypted_file` (which detects at-rest TRENC
        ciphertext produced by the worker), this detects the browser-produced
        ``FENCR`` format. Both formats may coexist, so callers should probe
        FENCR first, then TRENC.
        """
        if isinstance(path, bytes):
            return path.startswith(_FENCR_MAGIC)
        try:
            with open(path, "rb") as f:
                return f.read(len(_FENCR_MAGIC)) == _FENCR_MAGIC
        except OSError:
            return False

    def iter_decrypt_fencr(
        self,
        read_chunk: Callable[[int], bytes],
        data_key: bytes,
    ) -> Iterator[bytes]:
        """
        Yield plaintext chunks from a FENCR v1 blob via a chunk-reading callback.

        Memory-bounded: the whole blob is never loaded into memory. The caller
        supplies a ``read_chunk(n)`` callback (e.g. a file object's ``read`` or
        a Minio ``get_object`` stream).

        Args:
            read_chunk: Callable returning exactly ``n`` bytes (or fewer at end).
            data_key: The raw 32-byte per-file key (already unwrapped by the
                caller from its at-rest ciphertext form).

        Raises:
            ValueError: If the header is missing/invalid or the version is not v1.
        """
        header = read_chunk(_FENCR_HEADER_LEN)
        if len(header) != _FENCR_HEADER_LEN or not header.startswith(_FENCR_MAGIC):
            raise ValueError("Not a client-encrypted (FENCR) blob (bad header)")

        version = header[len(_FENCR_MAGIC)]
        if version != _FENCR_VERSION[0]:
            raise ValueError(f"Unsupported FENCR version: {version}")

        chunk_size = int.from_bytes(
            header[len(_FENCR_MAGIC) + 1: len(_FENCR_MAGIC) + 5], "big"
        )
        salt = header[len(_FENCR_MAGIC) + 5: len(_FENCR_MAGIC) + 5 + _FENCR_SALT_LEN]
        nonce_prefix = header[
            len(_FENCR_MAGIC) + 5 + _FENCR_SALT_LEN: _FENCR_HEADER_LEN
        ]
        if chunk_size <= 0:
            raise ValueError("Invalid FENCR chunk_size (must be positive)")

        file_key = self._derive_fencr_file_key(salt, data_key)
        cipher = AESGCM(file_key)

        counter = 0
        while True:
            chunk = read_chunk(chunk_size + _FENCR_TAG_LEN)  # ciphertext + GCM tag
            if not chunk:
                break
            if counter >= 2**32:
                raise OverflowError("File too large: FENCR chunk counter exhausted")
            # Each encryption message is a full chunk: 12-byte nonce = the
            # 8-byte per-file prefix + a 4-byte big-endian counter.
            nonce = nonce_prefix + counter.to_bytes(4, "big")
            yield cipher.decrypt(nonce, chunk, _FENCR_AAD)
            counter += 1

    def decrypt_fencr(self, src: BinaryIO, dst: BinaryIO, data_key: bytes) -> None:
        """Decrypt a FENCR v1 stream from ``src`` into ``dst``."""
        for chunk in self.iter_decrypt_fencr(src.read, data_key):
            dst.write(chunk)

    def decrypt_fencr_file(
        self,
        input_path: str | Path,
        output_path: str | Path,
        data_key: bytes,
    ) -> None:
        """Decrypt a FENCR v1 blob on disk into a plaintext file on disk."""
        with open(input_path, "rb") as src, open(output_path, "wb") as dst:
            self.decrypt_fencr(src, dst, data_key)

    def decrypt_fencr_bytes(self, blob: bytes, data_key: bytes) -> bytes:
        """In-memory convenience wrapper over :meth:`iter_decrypt_fencr`."""
        src = io.BytesIO(blob)
        dst = io.BytesIO()
        self.decrypt_fencr(src, dst, data_key)
        return dst.getvalue()

    def encrypt_bytes(self, data: bytes, user_id: str) -> bytes:
        """In-memory wrapper over the streaming format."""
        src = io.BytesIO(data)
        dst = io.BytesIO()
        self.encrypt_stream(src, dst, user_id)
        return dst.getvalue()

    def decrypt_bytes(self, ciphertext: bytes, user_id: str) -> bytes:
        """In-memory wrapper over the streaming format."""
        src = io.BytesIO(ciphertext)
        dst = io.BytesIO()
        self.decrypt_stream(src, dst, user_id)
        return dst.getvalue()

    # ------------------------------------------------------------------
    # Key management
    # ------------------------------------------------------------------

    @property
    def master_key(self) -> bytes:
        """Return the master key (for secure storage)."""
        return self._master_key

    @classmethod
    def from_base64_key(cls, key_b64: str) -> "FileEncryptionService":
        """Create the service from a base64-encoded Fernet key."""
        return cls(master_key=key_b64.encode("utf-8"))


def get_file_encryption_service() -> "FileEncryptionService | None":
    """
    Build the encryption service from ``ENCRYPTION_MASTER_KEY``.

    Returns ``None`` when no master key is configured, which disables
    encryption at rest (plaintext files in object storage).
    """
    from src.infrastructure.config.settings import get_settings

    settings = get_settings()
    if not settings.ENCRYPTION_MASTER_KEY:
        return None
    return FileEncryptionService.from_base64_key(
        settings.ENCRYPTION_MASTER_KEY.get_secret_value()
    )

