"""Email-verification token rules.

The token is the only thing standing between "I typed someone else's address"
and "I control that mailbox", so its properties matter:

* **High entropy, generated by ``secrets``.** ``token_urlsafe(32)`` is 32
  CSPRNG bytes → 43 URL-safe characters. It must be guessable-proof because it
  is the sole credential in the link — there is no second factor.
* **Only the hash is persisted.** A database leak (backup, replica, log dump)
  must not hand an attacker the ability to verify — and therefore take over —
  arbitrary accounts. This mirrors the API-key handling in
  ``domain/security/enitities/api_key.py``.
* **SHA-256, not Argon2.** The usual reason to use a slow password hash is that
  passwords are low-entropy and attacker-guessable. A 256-bit random token is
  not, so a fast hash is sufficient and keeps verification a single indexed
  lookup instead of a CPU-bound scan. Do not "harden" this to Argon2: it would
  add latency to every verification without reducing risk.
* **Single-use and time-boxed.** ``consume`` clears the stored hash, so a
  replayed link fails; the expiry bounds the window in which a leaked mailbox
  or browser history entry is exploitable.
"""

import hashlib
import secrets
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

#: Bytes of CSPRNG entropy per token (43 URL-safe characters once encoded).
TOKEN_BYTES = 32


@dataclass(frozen=True)
class IssuedVerificationToken:
    """A freshly minted token: the value to email, and what to store."""

    #: The value that goes in the link. Never persisted.
    raw: str
    #: SHA-256 hex digest, the only form written to the database.
    hashed: str
    #: Instant after which the token is rejected.
    expires_at: datetime


def hash_verification_token(raw: str) -> str:
    """Return the storable digest of a raw token.

    Deliberately un-salted: verification looks the row up *by* this digest, so
    a per-row salt would make the lookup impossible. Salting adds nothing here
    anyway — there is no dictionary of likely tokens to precompute against.
    """
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def issue_verification_token(
    *,
    ttl_hours: int,
    now: datetime | None = None,
) -> IssuedVerificationToken:
    """Mint a new verification token valid for ``ttl_hours``.

    ``now`` is injectable so expiry behaviour is testable without patching the
    clock. Naive datetimes are rejected rather than silently assumed to be UTC:
    a naive/aware comparison raises ``TypeError`` deep in a request handler,
    which is a far worse failure than a clear error at the call site.
    """
    reference = now or datetime.now(UTC)
    if reference.tzinfo is None:
        raise ValueError("issue_verification_token requires a timezone-aware 'now'")

    raw = secrets.token_urlsafe(TOKEN_BYTES)
    return IssuedVerificationToken(
        raw=raw,
        hashed=hash_verification_token(raw),
        expires_at=reference + timedelta(hours=ttl_hours),
    )


def token_is_expired(expires_at: datetime | None, *, now: datetime | None = None) -> bool:
    """True when ``expires_at`` has been reached (or is missing).

    A missing expiry is treated as expired — fail closed. That state should be
    unreachable (the token is issued with one), but if a row ever ends up
    without it, accepting the token would make it valid forever.

    Uses ``>=`` so that a token whose deadline is *exactly now* counts as
    expired. This must agree with the activation statement in the users router,
    which filters on ``email_verification_expires_at > now`` and therefore also
    excludes the exact deadline. If the two disagreed, the request would pass
    this check and then silently fail to match any row — an "invalid link"
    error for a token that had just been reported live.
    """
    if expires_at is None:
        return True
    reference = now or datetime.now(UTC)
    expires = expires_at
    if expires.tzinfo is None:
        # SQLite (used by the test suite) round-trips ``DateTime(timezone=True)``
        # as a naive value; PostgreSQL returns it aware. Normalise rather than
        # relying on the backend.
        expires = expires.replace(tzinfo=UTC)
    return reference >= expires


def cooldown_elapsed(
    sent_at: datetime | None,
    *,
    cooldown_seconds: int,
    now: datetime | None = None,
) -> bool:
    """True when a new verification email may be sent for this account.

    ``sent_at`` of ``None`` (never sent) always permits a send, as does a
    non-positive cooldown — so a deployment that wants no limit can express that
    without a separate code path.
    """
    if sent_at is None or cooldown_seconds <= 0:
        return True
    reference = now or datetime.now(UTC)
    previous = sent_at
    if previous.tzinfo is None:
        previous = previous.replace(tzinfo=UTC)
    return reference >= previous + timedelta(seconds=cooldown_seconds)
