"""Email-verification token rules.

The token is the only thing standing between "I typed someone else's address"
and "I control that mailbox", so its properties matter:

* **High entropy, generated by ``secrets``.** ``token_urlsafe(32)`` is 32
  CSPRNG bytes → 43 URL-safe characters. It must be guessable-proof because it
  is the sole credential in the link — there is no second factor.
* **Only the hash is persisted.** A database leak (backup, replica, log dump)
  must not hand an attacker the ability to verify — and therefore take over —
  arbitrary accounts. This mirrors the API-key handling in
  ``domain/security/enitities/api_key.py``.
* **SHA-256, not Argon2.** The usual reason to use a slow password hash is that
  passwords are low-entropy and attacker-guessable. A 256-bit random token is
  not, so a fast hash is sufficient and keeps verification a single indexed
  lookup instead of a CPU-bound scan. Do not "harden" this to Argon2: it would
  add latency to every verification without reducing risk.
* **Single-use and time-boxed.** ``consume`` clears the stored hash, so a
  replayed link fails; the expiry bounds the window in which a leaked mailbox
  or browser history entry is exploitable.

The implementation of all of the above now lives in ``one_time_token``, because
a password-reset token has exactly the same properties and one shared
implementation is one thing to audit. This module is the
verification-named façade the rest of the codebase imports, and its public API
is unchanged: ``TOKEN_BYTES``, ``IssuedVerificationToken``,
``hash_verification_token``, ``issue_verification_token``, ``token_is_expired``
and ``cooldown_elapsed``.
"""

from datetime import datetime, timedelta

from src.domain.security.enitities.one_time_token import (
    TOKEN_BYTES,
    IssuedToken,
    cooldown_elapsed,
    hash_token as hash_verification_token,
    issue_token,
    token_is_expired,
)

__all__ = [
    "TOKEN_BYTES",
    "IssuedVerificationToken",
    "cooldown_elapsed",
    "hash_verification_token",
    "issue_verification_token",
    "token_is_expired",
]

#: A verification token and a reset token are the same value object, so the
#: published name is an alias rather than a parallel class that could drift.
IssuedVerificationToken = IssuedToken


def issue_verification_token(
    *,
    ttl_hours: int,
    now: datetime | None = None,
) -> IssuedVerificationToken:
    """Mint a new verification token valid for ``ttl_hours``.

    ``now`` is injectable so expiry behaviour is testable without patching the
    clock. Naive datetimes are rejected rather than silently assumed to be UTC:
    a naive/aware comparison raises ``TypeError`` deep in a request handler,
    which is a far worse failure than a clear error at the call site.
    """
    return issue_token(ttl=timedelta(hours=ttl_hours), now=now)
