"""Tests for the encrypted streaming download helper."""

import asyncio
import io

import pytest

from src.infrastructure.adapters.security.encryption import FileEncryptionService
from src.infrastructure.adapters.storage.minio_storage_adapter import MinioFileStorageAdapter
from src.presentation.api.dependencies.download_stream import iter_decrypted_object


def _make_service() -> FileEncryptionService:
    """Build a service with a throwaway auto-generated key (tests only)."""
    return FileEncryptionService(allow_autogenerated_key=True)


class FakeStreamResponse:
    """Mimics the minio get_object response object (read/close)."""

    def __init__(self, payload: bytes):
        self._buf = io.BytesIO(payload)
        self.closed = False

    def read(self, n: int = -1) -> bytes:
        return self._buf.read(n)

    def close(self) -> None:
        self.closed = True


class FakeStreamingStorage(MinioFileStorageAdapter):
    """MinioFileStorageAdapter stand-in that returns an in-memory stream."""

    def __init__(self, payload: bytes):
        super().__init__(bucket_name="test", s3_client=None)  # type: ignore[arg-type]
        self._payload = payload
        self.last_response: FakeStreamResponse | None = None

    def get_object_stream(self, key: str):
        self.last_response = FakeStreamResponse(self._payload)
        return self.last_response


def test_iter_decrypted_object_streams_plaintext_object() -> None:
    """A non-encrypted object (direct browser upload) streams through as-is.

    Regression test for the 0-byte download bug: uploads are written to object
    storage plaintext, so the download path must NOT try to "decrypt" them.
    Previously it raised ``Not a Transform-encrypted file (bad header)`` and
    returned an empty body.
    """
    service = _make_service()
    plaintext = b"%PDF-1.7 real plaintext upload bytes" * 500
    storage = FakeStreamingStorage(plaintext)

    async def _run() -> bytes:
        chunks = []
        async for chunk in iter_decrypted_object(storage, "upload.pdf", service, "7"):
            chunks.append(chunk)
        return b"".join(chunks)

    result = asyncio.run(_run())
    assert result == plaintext
    assert storage.last_response is not None
    assert storage.last_response.closed


def test_iter_decrypted_object_decrypts_ciphertext() -> None:
    """Real ciphertext still decrypts correctly through the download path."""
    service = _make_service()
    ciphertext = service.encrypt_bytes(b"secret document" * 1000, "7")
    storage = FakeStreamingStorage(ciphertext)

    async def _run() -> bytes:
        chunks = []
        async for chunk in iter_decrypted_object(storage, "input.enc", service, "7"):
            chunks.append(chunk)
        return b"".join(chunks)

    plaintext = asyncio.run(_run())
    assert plaintext == b"secret document" * 1000
    assert storage.last_response is not None
    assert storage.last_response.closed


def test_iter_decrypted_object_closes_response_on_error() -> None:
    service = _make_service()
    # Real ciphertext for user "7", decrypted as a different user → InvalidTag.
    # This is the true failure path and must still close the stream.
    ciphertext = service.encrypt_bytes(b"for another user", "7")
    storage = FakeStreamingStorage(ciphertext)

    async def _run() -> None:
        async for _ in iter_decrypted_object(storage, "x.enc", service, "8"):
            pass

    with pytest.raises(Exception):
        asyncio.run(_run())

    assert storage.last_response is not None
    assert storage.last_response.closed


def test_iter_decrypted_object_wrong_user_fails() -> None:
    service = _make_service()
    ciphertext = service.encrypt_bytes(b"for another user", "7")
    storage = FakeStreamingStorage(ciphertext)

    async def _run() -> None:
        async for _ in iter_decrypted_object(storage, "x.enc", service, "8"):
            pass

    with pytest.raises(Exception):
        asyncio.run(_run())

    assert storage.last_response is not None
    assert storage.last_response.closed
