"""Tests for the encryption service."""

import base64

import pytest
from cryptography.fernet import Fernet

from src.infrastructure.adapters.security.encryption import (
    DEFAULT_CHUNK_SIZE,
    FileEncryptionService,
)


def _make_service() -> FileEncryptionService:
    """Build a service with a throwaway auto-generated key (tests only)."""
    return FileEncryptionService(allow_autogenerated_key=True)


def _make_key() -> bytes:
    return Fernet.generate_key()


class TestFileEncryptionService:
    """Tests for AES-256-GCM file encryption with per-user keys."""

    def test_encrypt_decrypt_roundtrip(self):
        """Encrypt and decrypt should produce the original data."""
        service = _make_service()
        original = b"Hello, this is secret file content!"
        user_id = "user-123"

        encrypted = service.encrypt_file(original, user_id)
        assert encrypted != original
        assert len(encrypted) > len(original)

        decrypted = service.decrypt_file(encrypted, user_id)
        assert decrypted == original

    def test_different_users_have_different_keys(self):
        """Different users should get different encryption keys."""
        service = _make_service()
        data = b"test data"

        encrypted_a = service.encrypt_file(data, "user-a")
        encrypted_b = service.encrypt_file(data, "user-b")

        # Ciphertexts should be different because keys differ
        assert encrypted_a != encrypted_b

    def test_cannot_decrypt_with_wrong_user(self):
        """Decrypting with a different user ID should fail."""
        service = _make_service()
        data = b"secret"

        encrypted = service.encrypt_file(data, "user-a")

        with pytest.raises(Exception):
            service.decrypt_file(encrypted, "user-b")

    def test_master_key_persistence(self):
        """Service should expose its master key."""
        service = _make_service()
        key = service.master_key
        assert len(key) > 0
        assert isinstance(key, bytes)

    def test_from_base64_key(self):
        """Creating from a base64 key should work."""
        key = _make_key()
        key_b64 = key.decode()

        service = FileEncryptionService(master_key=key)

        # Encrypt with the service
        data = b"test"
        encrypted = service.encrypt_file(data, "user-1")

        # Create a new service from the same key
        service2 = FileEncryptionService.from_base64_key(key_b64)
        decrypted = service2.decrypt_file(encrypted, "user-1")
        assert decrypted == data

    def test_empty_data(self):
        """Empty data should still encrypt and decrypt."""
        service = _make_service()
        encrypted = service.encrypt_file(b"", "user-1")
        decrypted = service.decrypt_file(encrypted, "user-1")
        assert decrypted == b""

    def test_large_data(self):
        """Large data should encrypt and decrypt correctly."""
        service = _make_service()
        data = b"x" * (1024 * 1024)  # 1MB

        encrypted = service.encrypt_file(data, "user-1")
        decrypted = service.decrypt_file(encrypted, "user-1")
        assert decrypted == data

    # -- Key hardening -----------------------------------------------------

    def test_no_key_raises_without_opt_in(self):
        """Silently auto-generating a key on no master key is a footgun."""
        with pytest.raises(ValueError, match="master_key is required"):
            FileEncryptionService()

    def test_malformed_key_rejected(self):
        """A non-base64 master key must be rejected at construction."""
        with pytest.raises(ValueError, match="not a valid base64"):
            FileEncryptionService(master_key=b"\x00\x01\x02 not-base64")

    def test_short_key_rejected(self):
        """A key that is not a 32-byte Fernet key must be rejected."""
        # A valid base64 value that decodes to 16 bytes, not 32.
        short_key = __import__("base64").urlsafe_b64encode(b"x" * 16)
        with pytest.raises(ValueError, match="32-byte Fernet key"):
            FileEncryptionService(master_key=short_key)

    def test_previous_key_also_validated(self):
        """Previous keys passed for rotation are validated too."""
        short_key = __import__("base64").urlsafe_b64encode(b"x" * 16)
        with pytest.raises(ValueError, match="32-byte Fernet key"):
            FileEncryptionService(
                master_key=_make_key(), previous_master_keys=[short_key]
            )


class TestStreamingEncryption:
    """Tests for the chunked AES-256-GCM streaming format."""

    def _roundtrip(self, data: bytes, user_id: str = "user-1") -> bytes:
        service = _make_service()
        return service.decrypt_bytes(service.encrypt_bytes(data, user_id), user_id)

    def test_streaming_roundtrip_small(self):
        assert self._roundtrip(b"small payload") == b"small payload"

    def test_streaming_roundtrip_multi_chunk(self):
        # 2.5 MiB forces multiple 1 MiB chunks
        data = bytes(range(256)) * 10240  # ~2.5 MiB
        assert self._roundtrip(data) == data

    def test_streaming_roundtrip_exact_chunk_boundary(self):
        data = b"x" * DEFAULT_CHUNK_SIZE
        assert self._roundtrip(data) == data

    def test_streaming_roundtrip_crosses_chunk_boundary(self):
        data = b"y" * (DEFAULT_CHUNK_SIZE + 1)
        assert self._roundtrip(data) == data

    def test_streaming_empty_file(self):
        assert self._roundtrip(b"") == b""

    def test_streaming_encrypts_at_rest(self):
        service = _make_service()
        ciphertext = service.encrypt_bytes(b"secret", "user-1")
        # header magic present, plaintext not visible
        assert ciphertext.startswith(b"TRENC")
        assert b"secret" not in ciphertext

    def test_streaming_wrong_user_fails(self):
        service = _make_service()
        ciphertext = service.encrypt_bytes(b"secret", "user-a")
        with pytest.raises(Exception):
            service.decrypt_bytes(ciphertext, "user-b")

    def test_streaming_tamper_detected(self):
        service = _make_service()
        ciphertext = bytearray(service.encrypt_bytes(b"attack surface", "user-1"))
        ciphertext[-1] ^= 0xFF  # flip a bit in the final tag/byte
        with pytest.raises(Exception):
            service.decrypt_bytes(bytes(ciphertext), "user-1")

    def test_streaming_rejects_foreign_header(self):
        service = _make_service()
        with pytest.raises(ValueError, match="Not a Transform-encrypted file"):
            service.decrypt_bytes(b"not-encrypted-data", "user-1")

    def test_streaming_file_path_api_roundtrip(self, tmp_path):
        service = _make_service()
        plain = tmp_path / "plain.bin"
        encrypted = tmp_path / "plain.bin.enc"
        decrypted = tmp_path / "decrypted.bin"

        plain.write_bytes(b"file based streaming roundtrip" * 1000)

        service.encrypt_file_to(plain, encrypted, "user-1")
        assert encrypted.exists()
        assert plain.read_bytes() not in encrypted.read_bytes()

        service.decrypt_file_to(encrypted, decrypted, "user-1")
        assert decrypted.read_bytes() == plain.read_bytes()

    def test_is_encrypted_file_true_for_ciphertext_and_false_for_plaintext(self, tmp_path):
        """is_encrypted_file must distinguish ciphertext from plaintext objects.

        This is critical because uploads are written to object storage directly
        from the browser (plaintext) even when a master key is configured; the
        worker and download path must only decrypt objects that are actually
        ciphertext, otherwise plaintext uploads fail with a bad-header error and
        produce 0-byte outputs.
        """
        service = _make_service()
        plain = tmp_path / "upload.pdf"
        plain.write_bytes(b"%PDF-1.7 real document bytes")

        encrypted = tmp_path / "upload.pdf.enc"
        service.encrypt_file_to(plain, encrypted, "user-1")

        assert service.is_encrypted_file(encrypted) is True
        assert service.is_encrypted_file(plain) is False

    def test_is_encrypted_file_missing_path_returns_false(self, tmp_path):
        service = _make_service()
        missing = tmp_path / "does-not-exist.bin"
        assert service.is_encrypted_file(missing) is False

    def test_streaming_reuses_master_key_across_services(self):
        key = _make_key()
        svc1 = FileEncryptionService(master_key=key)
        svc2 = FileEncryptionService.from_base64_key(key.decode())

        ciphertext = svc1.encrypt_bytes(b"shared key", "user-1")
        assert svc2.decrypt_bytes(ciphertext, "user-1") == b"shared key"

    def test_iter_decrypt_streams_in_chunks(self):
        """iter_decrypt must yield identical plaintext via a reader callback."""
        service = _make_service()
        data = b"streaming reader payload" * 200_000  # ~4.5 MiB, multiple chunks
        ciphertext = service.encrypt_bytes(data, "user-1")

        pos = 0

        def read_n(n: int) -> bytes:
            nonlocal pos
            chunk = ciphertext[pos:pos + n]
            pos += len(chunk)
            return chunk

        decrypted = b"".join(service.iter_decrypt(read_n, "user-1"))
        assert decrypted == data

    def test_iter_decrypt_detects_tamper(self):
        service = _make_service()
        ciphertext = bytearray(service.encrypt_bytes(b"tamper me", "user-1"))
        ciphertext[-1] ^= 0x01

        pos = 0

        def read_n(n: int) -> bytes:
            nonlocal pos
            chunk = bytes(ciphertext[pos:pos + n])
            pos += len(chunk)
            return chunk

        with pytest.raises(Exception):
            for _ in service.iter_decrypt(read_n, "user-1"):
                pass

    # -- AAD binding -------------------------------------------------------

    def test_streaming_tamper_in_payload_fails_auth(self):
        """Flipping a byte in the middle of the payload must fail auth."""
        service = _make_service()
        data = b"secret" * 10  # multi-chunk to avoid hitting only the last tag
        ciphertext = bytearray(service.encrypt_bytes(data, "user-1"))
        # Flip a byte a little past the header, in the first chunk ciphertext.
        ciphertext[len(b"TRENC") + 1 + 4 + 16 + 8 + 2] ^= 0x01
        with pytest.raises(Exception):
            service.decrypt_bytes(bytes(ciphertext), "user-1")

    def test_streaming_aad_binds_ciphertext_to_user(self):
        """A ciphertext for user A must not decrypt under user B even with the
        same master key (identity is bound via AAD + key derivation)."""
        key = _make_key()
        svc = FileEncryptionService(master_key=key)
        ciphertext = svc.encrypt_bytes(b"identity-bound", "user-a")
        with pytest.raises(Exception):
            svc.decrypt_bytes(ciphertext, "user-b")

    # -- Key rotation ------------------------------------------------------

    def test_key_rotation_decrypts_with_previous_key(self):
        """Decrypt falls back to a previous master key on auth failure."""
        key_a = _make_key()
        key_b = _make_key()

        # File encrypted under the old key A.
        old_service = FileEncryptionService(master_key=key_a)
        data = b"rotated secret document"
        ciphertext = old_service.encrypt_bytes(data, "user-1")

        # New service carries the current key B first, then the previous key A.
        rotated = FileEncryptionService(
            master_key=key_b, previous_master_keys=[key_a]
        )
        assert rotated.decrypt_bytes(ciphertext, "user-1") == data

    def test_key_rotation_prefers_current_key(self):
        """The current key is tried first; a previous key only as fallback."""
        key_a = _make_key()
        key_b = _make_key()

        old_service = FileEncryptionService(master_key=key_a)
        ciphertext = old_service.encrypt_bytes(b"data", "user-1")

        # Service without the previous key cannot decrypt.
        fresh = FileEncryptionService(master_key=key_b)
        with pytest.raises(Exception):
            fresh.decrypt_bytes(ciphertext, "user-1")

    def test_key_rotation_backward_compatible_header(self):
        """Rotation does not change the on-disk header/format."""
        key_a = _make_key()
        service = FileEncryptionService(master_key=key_a)
        ciphertext = service.encrypt_bytes(b"format stable", "user-1")
        # Header magic, version, and layout are unchanged.
        assert ciphertext.startswith(b"TRENC\x01")
        # Decryptable directly by the same key service (no rotation needed).
        assert FileEncryptionService(master_key=key_a).decrypt_bytes(
            ciphertext, "user-1"
        ) == b"format stable"


# ---------------------------------------------------------------------------
# Client-side encryption ("FENCR")
# ---------------------------------------------------------------------------

class TestClientSideFencrEncryption:
    """Tests for the browser-produced FENCR decrypt format.

    The FENCR format is produced by WebCrypto in the browser and must be
    byte-compatible with the Python mirror. The golden vector below is the
    authoritative cross-language check: re-encrypting the same inputs in the
    browser must produce the exact blob the server decrypts.
    """

    # Golden vector (do not change):
    #   data_key     = bytes([0x42]) * 32
    #   salt         = bytes(range(1, 17))
    #   nonce_prefix = bytes([0xAA]) * 8
    #   chunk_size   = 16
    #   plaintext    = b"hello world"
    #   full_blob_b64 = "RkVOQ1IBAAAAEAECAwQFBgcICQoLDA0ODxCqqqqqqqqqqmo21IilUFfrmkg3QRBlt8YA8GfN3r+gZ/Swag=="
    DATA_KEY_HEX = "4242424242424242424242424242424242424242424242424242424242424242"
    FILE_KEY_HEX = "1ea3caeecd8f537ce8c168328a16890f718c1689145494b1c23f105d0ec8fef5"
    GOLDEN_BLOB_B64 = (
        "RkVOQ1IBAAAAEAECAwQFBgcICQoLDA0ODxCqqqqqqqqqqmo21IilUFfrmkg3QRBlt8YA8GfN3r+gZ/Swag=="
    )

    def _data_key(self) -> bytes:
        return bytes.fromhex(self.DATA_KEY_HEX)

    def test_golden_vector_decrypts_to_hello_world(self):
        """The authoritative cross-language compatibility check."""
        service = _make_service()
        blob = base64.b64decode(self.GOLDEN_BLOB_B64)

        plaintext = service.decrypt_fencr_bytes(blob, self._data_key())

        assert plaintext == b"hello world"

    def test_golden_vector_is_fencr_file(self):
        """The blob must satisfy the FENCR magic probe."""
        service = _make_service()
        blob = base64.b64decode(self.GOLDEN_BLOB_B64)

        assert service.is_fencr_file(blob) is True

    def test_is_fencr_file_rejects_plaintext_and_trenc(self):
        """is_fencr_file must only match the FENCR magic, not other formats."""
        service = _make_service()
        assert service.is_fencr_file(b"plain text") is False
        assert service.is_fencr_file(b"TRENC\x01") is False

    def test_fencr_file_path_roundtrip(self, tmp_path):
        """Streaming file-based decrypt must reproduce plaintext."""
        service = _make_service()
        blob = base64.b64decode(self.GOLDEN_BLOB_B64)

        encrypted = tmp_path / "client-encrypted.bin"
        decrypted = tmp_path / "decrypted.txt"
        encrypted.write_bytes(blob)

        service.decrypt_fencr_file(encrypted, decrypted, self._data_key())
        assert decrypted.read_bytes() == b"hello world"

    def test_fencr_rejects_bad_header(self):
        """A non-FENCR stream must raise a clear ValueError."""
        service = _make_service()
        with pytest.raises(ValueError, match="Not a client-encrypted"):
            service.decrypt_fencr_bytes(b"not-a-fencr-blob", self._data_key())

    def test_fencr_rejects_unsupported_version(self):
        """A FENCR blob with a non-v1 version must be rejected."""
        service = _make_service()
        blob = bytearray(base64.b64decode(self.GOLDEN_BLOB_B64))
        blob[5] = 0x02  # version byte
        with pytest.raises(ValueError, match="Unsupported FENCR version"):
            service.decrypt_fencr_bytes(bytes(blob), self._data_key())

    def test_fencr_wrong_data_key_detects_tamper(self):
        """Decrypting with the wrong data key must fail authentication."""
        service = _make_service()
        blob = base64.b64decode(self.GOLDEN_BLOB_B64)
        wrong_key = b"\x00" * 32
        with pytest.raises(Exception):
            service.decrypt_fencr_bytes(blob, wrong_key)

    def test_fencr_multi_chunk_roundtrip(self):
        """A FENCR blob split across several chunks must decrypt fully."""
        service = _make_service()
        data_key = self._data_key()
        salt = bytes(range(1, 17))
        nonce_prefix = bytes([0xAA]) * 8
        chunk_size = 16
        plaintext = b"hello world, hello again, more data"  # > 1 chunk

        # Build a multi-chunk FENCR blob in Python (mirroring WebCrypto).
        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        from cryptography.hazmat.primitives.kdf.hkdf import HKDF

        file_key = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            info=b"transform-client-v1:enc",
        ).derive(data_key)
        cipher = AESGCM(file_key)
        aad = b"transform-client-v1"

        header = b"FENCR" + b"\x01" + chunk_size.to_bytes(4, "big") + salt + nonce_prefix
        body = b""
        counter = 0
        for i in range(0, len(plaintext), chunk_size):
            chunk = plaintext[i:i + chunk_size]
            nonce = nonce_prefix + counter.to_bytes(4, "big")
            body += cipher.encrypt(nonce, chunk, aad)
            counter += 1
        blob = header + body

        assert service.decrypt_fencr_bytes(blob, data_key) == plaintext

    def test_fencr_iter_decrypt_streams_in_chunks(self):
        """iter_decrypt_fencr yields identical plaintext via a reader callback."""
        service = _make_service()
        blob = base64.b64decode(self.GOLDEN_BLOB_B64)

        pos = 0

        def read_n(n: int) -> bytes:
            nonlocal pos
            chunk = blob[pos:pos + n]
            pos += len(chunk)
            return chunk

        decrypted = b"".join(service.iter_decrypt_fencr(read_n, self._data_key()))
        assert decrypted == b"hello world"
